targets:
  $default:
    builders:
      flamingo_generator|generator:
        enabled: true

builders:
  generator:
    import: "package:flamingo_generator/flamingo_generator.dart"
    builder_factories: ["enumHasValueBuilder"]
    build_extensions: {".dart": [".value.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]