targets:
  $default:
    builders:
      flamingo_generator|field_value_generator:
        enabled: true

builders:
  field_value_generator:
    import: "package:flamingo_generator/flamingo_generator.dart"
    builder_factories: ["fieldValueBuilder"]
    build_extensions: {".dart": [".flamingo.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]