name: flamingo_generator
description: Automatically generate code for converting flamingo JSON by annotating Dart classes.
version: 0.7.0+2
repository: https://github.com/hukusuke1007/flamingo

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: '>=0.39.5 <1.0.0'
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.4.2 <1.0.0'
  meta: '>=1.2.0 <2.0.0'
  source_gen: ^0.9.0
  flamingo_annotation: ^0.3.0

dev_dependencies:
  test:
  build_test:
