name: flamingo
description: Flamingo is a firesbase firestore model framework library.
  Flamingo manage DocumentReference and CollectionReference. And provide wrap interface of CRUD.
version: 0.5.2
homepage: https://twitter.com/hobbydevelop
repository: https://github.com/hukusuke1007/flamingo

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any