name: flamingo
description: This is Firebase Firestore Model Framework Library.
  Can be manage document reference and collection reference. And provide Firestore and Cloud Storage interface.
version: 1.3.0+1
repository: https://github.com/hukusuke1007/flamingo
homepage: https://github.com/hukusuke1007/flamingo

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.9.1