name: flamingo_annotation
description: Automatically generate code for converting flamingo JSON by annotating Dart classes.
version: 0.4.0
homepage: https://github.com/hukusuke1007/flamingo

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  # nothing

dev_dependencies:
  # nothing