name: flamingo_annotation
description: Automatically generate code for converting flamingo JSON by annotating Dart classes.
version: 0.2.0
homepage: https://twitter.com/hobbydevelop
repository: https://github.com/hukusuke1007/flamingo

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

