name: flamingo_example
description: Demonstrates how to use the flamingo plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  path_provider:
  pull_to_refresh:
  flutter_slidable:

  flamingo:
    path: ../
  flamingo_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.1
  # If occur analyzer error, please set build_resolvers.
  # build_resolvers: ^1.3.10

  flamingo_generator:

  test: ^1.14.4
#  cloud_firestore_mocks:
#  firebase_storage_mocks:


flutter:
  uses-material-design: true
  assets:
    - assets/
