name: flamingo_example
description: Demonstrates how to use the flamingo plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  path_provider: ^1.6.0
  pull_to_refresh: ^1.5.8

  flamingo:
    path: ../
  flamingo_annotation: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.1
  flamingo_generator: ^0.3.2

  test: ^1.14.4
#  cloud_firestore_mocks: ^0.4.4
#  firebase_storage_mocks: ^0.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/
